services:
  db:
    # Instead of running Wordpress on MariaDB, I wanted to try to get it running on MySQL.
    # The following line specifies to use MySQL instead of MariaDB
    image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060
    container_name: adam-mysql
  wordpress:
    image: wordpress:latest
    ports:
      - 8008:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    container_name: adam-wordpress
volumes:
  db_data:

  
    
